# Generated by Django 4.0 on 2022-06-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migram', '0007_post_user_profile_alter_post_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
