# Generated by Django 4.0 on 2022-06-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migram', '0009_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified',
        ),
    ]
